language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
  - ls -l
  - pwd
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - ls -l
deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  local_dir: build
  verbose: true
  edge: true
  on:
    branch: master
