language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  cleanup: true
  local_dir: build
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
