language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
before_deploy:
  - echo "deploy starting..."
  - cd $TRAVIS_BUILD_DIR/build
deploy:
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN
  verbose: true
  edge: true
  on:
    branch: master
